version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "mambaforge-23.11"

conda:
    environment: requirements/ncta.yml

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

python:
    install:
        - method: pip
          path: .
