version: 2

build:
    image: latest

conda:
    environment: requirements/docs.yml

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

python:
    install:
        - method: setuptools
          path: .
