[build-system]
# Defined by PEP 518
requires = [
  "setuptools>=42",
  "setuptools_scm[toml]>=6.0",
  "wheel",
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
  )/
)
'''

[tool.isort]
known_first_party = "nc_time_axis"
line_length = 79
profile = "black"
skip_gitignore = "True"
verbose = "False"

[tool.pytest.ini_options]
addopts = "-ra -v --doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS NUMBER"
minversion = "6.0"
testpaths = "nc_time_axis"

[tool.setuptools_scm]
write_to = "src/nc_time_axis/_version.py"

[tool.check-manifest]
ignore = [
  "src/nc_time_axis/_version.py",
]
