.. comment
    Common resources in alphabetical order:

.. _cirrus-ci: https://cirrus-ci.org/
.. _cftime: https://unidata.github.io/cftime
.. _codespell: https://github.com/codespell-project/codespell
.. _conda: https://docs.conda.io/projects/conda/en/latest/index.html
.. _conda-lock: https://github.com/conda/conda-lock
.. _dependabot: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
.. _matplotlib: https://matplotlib.org/stable
.. _NEP29: https://numpy.org/neps/nep-0029-deprecation_policy.html
.. _netcdf4-python: https://github.com/Unidata/netcdf4-python
.. _numpy: https://numpy.org/doc/stable
.. _ORCID: https://orcid.org/
.. _PEP621: https://peps.python.org/pep-0621/
.. _pip: https://pip.pypa.io/en/stable
.. _pre-commit: https://pre-commit.com/
.. _pypi: https://pypi.org
.. _python: https://docs.python.org/3
.. _readthedocs: https://github.com/readthedocs/readthedocs.org
.. _test.pypi: https://test.pypi.org
.. _travis-ci: https://www.travis-ci.com/
.. _units registry: https://matplotlib.org/stable/api/units_api.html
.. _Zenodo: https://zenodo.org/


.. comment
    Core developers (@github names) in alphabetical order (surname):

.. _Pascal Bourgault: https://github.com/aulemahal
.. _Spencer Clark: https://github.com/spencerkclark
.. _Ruth Comer: https://github.com/rcomer
.. _Laura Dreyer: https://github.com/lbdreyer
.. _Phil Elson: https://github.com/pelson
.. _Mark Hedley: https://github.com/marqh
.. _Peter Killick: https://github.com/DPeterK
.. _Bill Little: https://github.com/bjlittle


.. comment
    Prolific contributors (@github names) in alphabetical order (surname):

.. _Filipe Fernandes: https://github.com/ocefpaf
