name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["2.7", "3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Python ${{ matrix.python-version }}
      run: |
        pip install coveralls
        pip install -e . --force-reinstall

    - name: Tests
      run: |
        coverage run setup.py test

    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}